name: Feature Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  mongoFeatureTests:
    name: Mongo FeatureTests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13, 3.14]
        mongodb-version: ['6.0', '7.0', '8.0']

    steps:
      - uses: actions/checkout@v2
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install

      - name: Run Mongo Feature Tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
          IN_LAYERS_TEST_MONGO_IMAGE: mongo:${{ matrix.mongodb-version }}
        run: poetry run behave -t ~@redis

  redisFeatureTests:
    name: Redis Stack FeatureTests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13, 3.14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install

      - name: Run Redis Stack Feature Tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: poetry run behave -t @redis
